### ISSUE TITLE
Generalizing to Non-Gaussian Elliptical Distributions

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/EllipticalSliceSampling.jl#22] opened 2021-10-18 19:26 UTC
As far as I can tell, there's nothing in this algorithm that makes it impossible to use, say, a multivariate t or multivariate logistic prior; could the code be generalized to handle this?

**Comment by devmotion** [comment] 2021-10-18 19:43
It's based on an invariance property of Gaussian distributions which does not hold for general elliptical distributions AFAIK (haven't checked; eq. 2 in the paper below). However, the algorithm can be generalized to more general target distributions without Gaussian prior by a construction that involves infinite mixtures of Gaussian, i.e., multivariate t distributions (introduces an additional auxiliary variable that is marginalized out, i.e., dropped from the samples): https://jmlr.org/papers/volume15/nishihara14a/nishihara14a.pdf

I'll close this issue since it seems to be mainly a duplicate of https://github.com/TuringLang/EllipticalSliceSampling.jl/issues/12.

**Closed by devmotion** 2021-10-18 19:43 UTC
